apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::541387229899:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-18XKMEC9FEQQF
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::541387229899:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-30T17:38:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1850"
  uid: 0b50224a-409c-4781-9160-af7b1a617b75
